/**
 * server.js
 * ---------
 * Vaultify's "dumb" backend server.
 *
 * Reminder: this server NEVER sees the real Master Password. It only
 * ever sees the Auth Key (derived in the browser via PBKDF2) and the
 * Encrypted Blob (gibberish it can't read).
 */

const express = require("express");
const app = express();

const PORT = 3000;

// Tells Express to automatically parse incoming JSON request bodies
// into a JavaScript object we can access via req.body.
app.use(express.json());

// --- FAKE "DATABASE" (temporary — Week 2 later step swaps this for a real one) ---
// In real Vaultify, authKey would be generated by the browser's PBKDF2
// step and never be a plain readable string like this.
const fakeUsersDB = {
  shubham: {
    authKey: "demo-auth-key-12345",
  },
};

// Test route — proves the server is alive.
app.get("/", (req, res) => {
  res.send("Vaultify backend is running! 🔐");
});

// LOGIN route.
// The browser sends: { "username": "shubham", "authKey": "..." }
app.post("/login", (req, res) => {
  const { username, authKey } = req.body;

  const user = fakeUsersDB[username];

  // Case 1: username doesn't exist at all
  if (!user) {
    return res.status(401).json({ success: false, message: "Invalid credentials" });
  }

  // Case 2: username exists, but the Auth Key doesn't match
  if (user.authKey !== authKey) {
    return res.status(401).json({ success: false, message: "Invalid credentials" });
  }

  // Case 3: everything matches — login succeeds
  // (Later step: replace this fake message with a real session token / JWT)
  res.json({ success: true, message: "Login successful!" });
});

app.listen(PORT, () => {
  console.log(`Vaultify server listening on http://localhost:${PORT}`);
});